# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.IntegerField(max_length=12)),
                ('national_id', models.IntegerField(max_length=14)),
                ('faculty', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('minor', models.CharField(max_length=100)),
                ('expected_year', models.IntegerField(max_length=4)),
                ('university', models.CharField(max_length=100)),
            ],
        ),
    ]
