# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASURT', '0002_applicants_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='expected_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='national_id',
            field=models.CharField(max_length=14),
        ),
    ]
