# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 04:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ASURT', '0004_applicants_profilepic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='profilepic',
        ),
    ]
