# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASURT', '0007_remove_applicants_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='mobile',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
